/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.gui;

import javax.swing.JOptionPane;
import pojo.UserProfile;

/**
 *
 * @author hp
 */
public class AdminOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionsFrame
     */
    public AdminOptionsFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblname.setText("Hello "+UserProfile.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Mypanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtnsetpaper = new javax.swing.JRadioButton();
        rbtneditpaper = new javax.swing.JRadioButton();
        rbtnregister = new javax.swing.JRadioButton();
        rbtnscores = new javax.swing.JRadioButton();
        btndotask = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mypanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("      Make  A  Choice");

        rbtnsetpaper.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnsetpaper);
        rbtnsetpaper.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnsetpaper.setForeground(new java.awt.Color(255, 255, 255));
        rbtnsetpaper.setText("Set A Paper");
        rbtnsetpaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnsetpaperActionPerformed(evt);
            }
        });

        rbtneditpaper.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtneditpaper);
        rbtneditpaper.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtneditpaper.setForeground(new java.awt.Color(255, 255, 255));
        rbtneditpaper.setText("Edit Paper");

        rbtnregister.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnregister);
        rbtnregister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnregister.setForeground(new java.awt.Color(255, 255, 255));
        rbtnregister.setText("Resister Student");
        rbtnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnregisterActionPerformed(evt);
            }
        });

        rbtnscores.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbtnscores);
        rbtnscores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnscores.setForeground(new java.awt.Color(255, 255, 255));
        rbtnscores.setText("View Scores");

        btndotask.setBackground(new java.awt.Color(0, 0, 0));
        btndotask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndotask.setForeground(new java.awt.Color(255, 255, 255));
        btndotask.setText("Do Task");
        btndotask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotaskActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ONLINE  QUIZ ADMINISTRATION PANEL");

        btnlogout.setForeground(new java.awt.Color(255, 51, 51));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        lblname.setBackground(new java.awt.Color(0, 0, 0));
        lblname.setForeground(new java.awt.Color(255, 51, 51));
        lblname.setText("Hello");

        jLabel3.setIcon(new javax.swing.ImageIcon("G:\\java core project files\\IMPORTANT PROJECT IMAGES\\admin (2).png")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout MypanelLayout = new javax.swing.GroupLayout(Mypanel);
        Mypanel.setLayout(MypanelLayout);
        MypanelLayout.setHorizontalGroup(
            MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbtnscores)
                        .addComponent(rbtnregister)
                        .addComponent(rbtneditpaper)
                        .addComponent(btndotask, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtnsetpaper))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
            .addGroup(MypanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MypanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addContainerGap())
        );
        MypanelLayout.setVerticalGroup(
            MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblname)
                    .addComponent(btnlogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MypanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(rbtnsetpaper)
                        .addGap(36, 36, 36)
                        .addComponent(rbtneditpaper)
                        .addGap(41, 41, 41)
                        .addComponent(rbtnregister)
                        .addGap(32, 32, 32)
                        .addComponent(rbtnscores)
                        .addGap(39, 39, 39)
                        .addComponent(btndotask, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mypanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        JOptionPane.showMessageDialog(null,"You have sucessfully logout");
        LoginFrame fr=new LoginFrame();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void rbtnsetpaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnsetpaperActionPerformed
    
    }//GEN-LAST:event_rbtnsetpaperActionPerformed

    private void btndotaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotaskActionPerformed
if(rbtnsetpaper.isSelected())
{
      SetPaperFrame ob=new SetPaperFrame();
      ob.setVisible(true);
      this.dispose();
}
else if(rbtneditpaper.isSelected())
{
    EditPaperFrame ed=new EditPaperFrame();
    ed.setVisible(true);
    this.dispose();
}
else if(rbtnregister.isSelected())
{
    StudentRegistrationFrame st=new StudentRegistrationFrame();
       st.setVisible(true);
       this.dispose();
}
else if(rbtnscores.isSelected())
{
    ViewScoreFrame fr=new ViewScoreFrame();
    fr.setVisible(true);
    this.dispose();
}
    }//GEN-LAST:event_btndotaskActionPerformed

    private void rbtnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnregisterActionPerformed
       
    }//GEN-LAST:event_rbtnregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mypanel;
    private javax.swing.JButton btndotask;
    private javax.swing.JButton btnlogout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblname;
    private javax.swing.JRadioButton rbtneditpaper;
    private javax.swing.JRadioButton rbtnregister;
    private javax.swing.JRadioButton rbtnscores;
    private javax.swing.JRadioButton rbtnsetpaper;
    // End of variables declaration//GEN-END:variables
}
